### ISSUE TITLE
Unable to Resolve module react-dom

### ISSUE THREAD

**Issue by brunnohofmann** [natura-cosmeticos/natds-rn#113]
**Describe the bug**
Ao instalar o DS em um projeto RN que usa Typescript, tenho recebido o erro abaixo: 

'Unable to resolve module 'react-dom' from 'node_modules/@naturacosmeticos/natds-rn/build/lib/common/Modal/WebModal.js': react-dom could not be found within the project.

![Screenshot_1603136658](https://user-images.githubusercontent.com/5169420/96503943-635e8f80-122a-11eb-9717-7dafe9f7e86a.png)

**To Reproduce**
1. Adicionar a lib natds-rn
2. Instalar o tema com o provider
3. Ver o erro

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Lib Version 3.0.0
 - OS: Android Pixel 2

You can also add information about your development environment if applicable (e.g. React and React native version)
Versão do React: 16.14.0
Versão do React-Native: 0.63.2

**Comment by arielwb** [comment]
Olá @brunnohofmann!

fixed in [3.0.1](https://www.npmjs.com/package/@naturacosmeticos/natds-rn/v/3.0.1)!

if the error persists, can you please reopen the issue?

**Comment by arielwb** [comment]
Issue resolvida 🎉 
Se o erro permanecer, pode reabrir a issue!
