### ISSUE TITLE
natds-rn v7.1 crashing after build the app

### ISSUE THREAD

**Issue by pedrorosarioo** [natura-cosmeticos/natds-rn#178]
**Describe the bug**
When i add the last version of the lib in my app, it starts crashing after build

**To Reproduce**
1. Create a new react native app `npx react-native init TestNaturaDesignSystemLibrary`
2. Install the natds-rn library `yarn add @naturacosmeticos/natds-rn`
3. In `App.js` build the theme object: 
```
import React from 'react';
... // other imports
import { buildTheme } from '@naturacosmeticos/natds-rn';

const theme = buildTheme('natura', 'light');

... // page code
```
4. Run the application: `npx react-native run-ios` or `npx react-native run-android`
5. See that the app crashes before render the page. It seems that the application tried to use styled-components but it is not a package from `@naturacosmetics/natds-rn`

**Expected behavior**
The application renders in the same way as a new application.

**Screenshots**
| iOS                     | Android |
| ----------------------------- | ------- |
| ![image](https://user-images.githubusercontent.com/26755665/123468868-bc0bd680-d5c8-11eb-8cca-a76b234b923b.png) | ![image](https://user-images.githubusercontent.com/26755665/123469197-1b69e680-d5c9-11eb-9721-5e12e3721011.png)

**Environment (please complete the following information):**
| software                      | version |
| ----------------------------- | ------- |
| iOS               | 14.4
| Simulator               | iPhone 12    
| react      | 17.0.1
| react-native | 0.64.2
| natds-rn         | ^7.1.0
| yarn                   | 1.22.10

You can also add information about your development environment if applicable (e.g. React and React native version)

**Additional context**

**Comment by lauralucca** [comment]
Olá, @pedrorosarioo! quando você instalou a `@naturacosmeticos/natds-rn` veio junto a `styled-components` versão 5 ou maior?

**Comment by pedrorosarioo** [comment]
Não não Laura, não instalou instalou nada da `styled-components` como dependência :/

**Comment by lauralucca** [comment]
Tenta instalar na mão para ver se resolve! Eu acredito que o yarn deveria ter instalado, a gente tem ela como peer dependency

**Comment by pedrorosarioo** [comment]
Oi @lauralucca, funcionou aqui após instalar a styled-components na mão ✅

**Comment by lauralucca** [comment]
Maravilha! Vou investigar mais sobre o yarn não instalar como esperado...  muuuito obrigada por nos informar, @pedrorosarioo! ❤️
